[package]
name = "rsonpath-lib"
version = "0.4.0"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath query engine powered by SIMD. Core library of `rsonpath`."
readme = "README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "parser"]
exclude = ["/tests", "/proptest-regressions"]
categories = [
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"
rust-version = "1.65.0"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
aligners = { version = "0.0.10", default-features = false }
cfg-if = "1.0.0"
log = "0.4.17"
md5 = "0.7.0"
memchr = { version = "2.5.0", optional = true }
memmap2 = "0.6.2"
nom = "7.1.3"
page_size = "0.5.0"
replace_with = { version = "0.1.7", optional = true }
smallvec = { version = "1.10.0", features = ["union"] }
static_assertions = "1.1.0"
thiserror = "1.0.40"
vector-map = "1.0.1"

[dev-dependencies]
itertools = "0.10.5"
pretty_assertions = "1.3.0"
proptest = "1.2.0"
test-case = "3.1.0"

[build-dependencies]
eyre = "0.6.8"

[features]
default = ["simd", "head-skip", "tail-skip", "unique-members"]
simd = ["aligners/simd"]
head-skip = ["dep:memchr"]
tail-skip = ["dep:replace_with"]
unique-members = ["tail-skip"]
